train_config:
  number_of_episodes: 10
  number_of_steps_in_episode: 50
  number_of_MTC_simulations: 50
  training_interval: 5
  max_depth: 2
  batch_size: 5
  train_verbal: True
  lr_NNr: 0.1
  lr_NNd: 0.1
  lr_NNp: 0.1
  look_ahead: 3
  look_back: 3
game: snake
game_size: 5
set_of_actions: [0, 1, 2, 3] # Right, left, up, down
head: True
game_over_reward: -999
exploration_rate: 1.41421
use_NN: True
snake_head_color: 
  - 255
  - 20
  - 147
snake_color: 
  - 255
  - 105
  - 180

