train_config:
  number_of_episodes: 50
  number_of_steps_in_episode: 50
  number_of_MTC_simulations: 100
  max_depth: 5
  batch_size: 5
  train_verbal: True
  lr_NNr: 0.1
  lr_NNd: 0.1
  lr_NNp: 0.1
game: snake
game_size: 5
set_of_actions: [0, 1, 2, 3] # Right, left, up, down
head: True
game_over_reward: -999
exploration_rate: 1.41421
use_NN: True