learning_rate: 0.01
state_dim: 64
abstract_state_dim: 14
action_dim: 1
reward_dim: 1
policy_dim: 4


representation:
  learning_rate: 0.01
  load: False 
  output_layer: linear
  layers: 
    - type: relu #relu, sigmoid, softmax, linear, etc.
      dim: 16
    - type: sigmoid
      dim: 16
 
dynamics:
  learning_rate: 0.01
  load: False
  output_layer: linear
  layers: 
    - type: relu #relu, sigmoid, softmax, linear, etc.
      dim: 16
    - type: sigmoid
      dim: 16

prediction:
  learning_rate: 0.01
  load: False
  policy_output_layer: softmax
  reward_output_layer: linear
  layers: 
    - type: relu #relu, sigmoid, softmax, linear, etc.
      dim: 16
    - type: sigmoid
      dim: 16